#STRIPE_SECRET_KEY:sk_test_51NDkYHSJl6QPJ1Yd9Y7mqH8syOOosa2dSxZOn8YNMWqWg33rixFZO9NhqhELsL5IZOq6wWdnTv3drJBslP7flI6J00uV5F2zvz
#  STRIPE_PUBLIC_KEY:pk_test_51NDkYHSJl6QPJ1YdWX1rRPSTFgCs7EZrlyq4dB8xr3FHIKzQEpB8FwViQM8mMZdbVZOnnny0N91c1lhYUm8GH6sN00Ua51UwFE
apiKey: rzp_test_BGPTgqrkVagzn6
secretKey: l48xX7CnwytQmBn5twVyiavo